### ISSUE TITLE
moment locale

### ISSUE THREAD

**Issue by ayhansipahi** [mattbradley/livestampjs#38]
it would be great if we can set locale inside livestamp.

**Comment by mattbradley** [comment]
The locale can be changed using the [Moment.js i18n functionality](http://momentjs.com/docs/#/i18n/). Since different versions of Moment.js have different ways of setting the locale, it would be easier to just use the existing Moment APIs for whatever version is being used instead of Livestamp trying to guess which version is loaded.

**Comment by micktaiwan** [comment]
Following moment docs
```
import moment from 'moment';
import 'moment/locale/fr';
moment.locale('fr');
```
This does not change livestamp's locale
